/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-114298-g97d2990ea6-20240321"
#endif /* AVUTIL_FFVERSION_H */
